# Site settings
name: Raúl Ricardo Amaya Sánchez
title: Raúl Amaya's site
email: raulricardo21@gmail.com
description: "This is Raúl Amaya's site. Frontend developer."
baseurl: ""
url: "http://raulamaya.net"

# Build settings
markdown: kramdown
permalinks: pretty
sass:
  style: :compressed
  sass_dir: _sass