# Site settings
name: Raúl Ricardo Amaya Sánchez
me:
  first_name: Raúl
  middle_name: Ricardo
  last_name: Amaya Sánchez
  header_name: Raúl Amaya
title: Raúl Amaya's site
email: raulricardo21@gmail.com
description: "This is Raúl Amaya's site. Frontend developer."
baseurl: ""
url: "http://raulamaya.net"

# Build settings
markdown: kramdown
permalinks: pretty


# Plugin: jekyll-assets
assets:
  compress:
    css:  sass
    js:   uglifier
  # Pathname of the destination of generated (bundled) assets relative
  # to the destination of the root.
  dirname: assets
  #
  # Base URL of assets paths.
  #
  baseurl: /assets/
  #
  # Pathnames where to find assets relative to the root of the site.
  #
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
  #
  # Sets JS compressor. No compression by default.
  # Possible variants: 'yui', 'uglifier', nil
  #
  js_compressor: ~
  #
  # Sets CSS compressor. No compression by default.
  # Possible variants: 'yui', 'sass', nil
  #
  css_compressor: sass
  #
  # Sets cachebusting policy for generated assets.
  #
  # Possible variants:
  #
  #   none - disables cachebusting
  #
  #     source file:  _assets/javascripts/app.css
  #     output file:  _site/assets/javascriptis/app.css
  #     output URL:   /assets/javascripts/app.css
  #
  #   soft - leave filenames as-is, but `?cb=<md5>` suffix for URLs generated
  #          with `asset_path`, `javascript` and `stylesheet`:
  #
  #     source file:  _assets/javascripts/app.css
  #     output file:  _site/assets/javascriptis/app.css
  #     output URL:   /assets/javascripts/app.css?cb=4f41243847da693a4f356c0486114bc6
  #
  #   hard - (default) injects cachebusting checksum into processed filename:
  #
  #     source file:  _assets/javascripts/app.css
  #     output file:  _site/assets/javascriptis/app-4f41243847da693a4f356c0486114bc6.css
  #     output URL:   /assets/javascripts/app-4f41243847da693a4f356c0486114bc6.css
  #
  cachebust: hard
  #
  # Whenever or not cache compiled assets (disabled by default).
  # See `Compilation Cache` section of README for details.
  #
  cache: false
  #
  # Specifies list of MIME types that needs to have gzipped versions.
  # You can set it to `false` to disable gzipping. Only javascripts and
  # stylesheets are gzipped by default.
  #
  gzip: [ text/css, application/javascript ]
  #
  # Does not concatenates files requested by `javascript` and `stylesheet`
  # helpers. Instead outputs multiple files in order they are required.
  # Default: false
  #
  debug: false

# Custom Variables
links:
  github: https://github.com/raulricardo
  googleplus: https://plus.google.com/u/0/+Ra%C3%BAlRicardoAmayaS%C3%A1nchez
  twitter: http://twitter.com/raulricard0

# sass:
#   sass_dir: _sass
#   style: :compressed
